package skywolf46.commandannotation.v4.test.exceptions

class TestSucceedException(val msg : String = "") : RuntimeException()